### ISSUE TITLE
currentConfiguration.isNotEmpty

### ISSUE THREAD

**Issue by bugrevealingbme** [jb3rndt/PersistentBottomNavBarV2#137] opened 2024-03-29 21:57 UTC
Package Version (from pubspec.yaml): persistent_bottom_nav_bar_v2: ^5.1.0

I had made such a code. If no tab has changed after opening the application, the application breaks. It happened after the last version.

```
if (index == currentIndex) {
      NavigationService.navigateMaybePop();
}
```

Logs:
E/flutter (14851): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:go_router/src/delegate.dart': Failed assertion: line 116 pos 7: 'currentConfiguration.isNotEmpty': You have popped the last page off of the stack, there are no pages left to show
E/flutter (14851): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (14851): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (14851): #2      GoRouterDelegate._debugAssertMatchListNotEmpty (package:go_router/src/delegate.dart:116:7)
E/flutter (14851): #3      GoRouterDelegate._completeRouteMatch.<anonymous closure> (package:go_router/src/delegate.dart:156:7)
E/flutter (14851): #4      GoRouterDelegate._completeRouteMatch (package:go_router/src/delegate.dart:158:6)
E/flutter (14851): #5      GoRouterDelegate._handlePopPageWithRouteMatch (package:go_router/src/delegate.dart:132:7)
E/flutter (14851): #6      _CustomNavigatorState._handlePopPage (package:go_router/src/builder.dart:416:42)
E/flutter (14851): #7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5284:28)
E/flutter (14851): #8      _PersistentTabViewState.build.<anonymous closure> (package:persistent_bottom_nav_bar_v2/components/persistent_tab_view.dart:334:23)
E/flutter (14851): <asynchronous suspension>
E/flutter (14851):

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A PersistentTabController was used after being disposed.
Once you have called dispose() on a PersistentTabController, it can no longer be used.

When the exception was thrown, this was the stack:
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:375:27)
#3      MainViewModelBase.dispose (package:date_planner/views_model/main_view_model/main_view_model.dart:207:19)
#4      MainView.build.<anonymous closure> (package:date_planner/views/main_view.dart:34:35)
#5      BaseViewState.dispose (package:date_planner/core/base_view.dart:47:52)
#6      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5689:11)
#7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2076:13)
#8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#15     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#41     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#43     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#44     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#45     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#46     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#47     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#49     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#50     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#51     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#52     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#53     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#55     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#56     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#58     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#59     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#61     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#62     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#64     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#65     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#66     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#67     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#68     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#69     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#70     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#71     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#72     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#73     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#74     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#76     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#77     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#79     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#80     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#81     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#82     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#83     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#85     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#86     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#87     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#88     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#89     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#91     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#92     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#93     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#94     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#95     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#97     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#98     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#99     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#100    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#101    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#103    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#104    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#105    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#106    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#107    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#109    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#110    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#111    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#112    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#113    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#115    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#116    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#117    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#118    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#119    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#121    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#122    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#123    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#124    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#125    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#126    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6856:16)
#127    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#128    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#129    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#130    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#131    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#133    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#134    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#135    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#136    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#137    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#138    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#139    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#140    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#141    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#142    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#143    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#145    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#146    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#147    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#148    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#149    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#150    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#151    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#152    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#153    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#154    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#155    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#156    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#157    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#158    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#159    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#160    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#161    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#162    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#163    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#164    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#165    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#166    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#167    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#168    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#169    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#170    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#171    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#172    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#173    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#174    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#175    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#176    ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#177    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2085:25)
#178    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2764:15)
#179    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3174:7)
#180    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:992:19)
#181    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#182    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#183    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#184    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#185    _invoke (dart:ui/hooks.dart:312:13)
#186    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#187    _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════

**Comment by BarryCarlyon** [comment] 2024-04-02 19:28
I'm seeing a similar error

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5013 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
```

When a user is on my "home page" and uses the android hardward button to go back.

I suspect it's the same issue even if caused by a different route.
Trying to go back from the home page/start point

**Comment by jb3rndt** [comment] 2024-04-03 16:52
Thanks for reporting. Closing this as duplicate of https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/139. @bugrevealingbme if you still have issues not covered by https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/139 feel free to open a new issue.

**Closed by jb3rndt** 2024-04-03 16:52 UTC

**Comment by bugrevealingbme** [comment] 2024-04-09 14:41
This bug has been fixed but there is another problem. If we pop on the first page it goes to the old tab. I don't want this to happen

https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/22865739/8fcd2686-b58d-4194-8237-1082b739b436

**Comment by jb3rndt** [comment] 2024-04-09 16:34
You can set `handleAndroidBackButtonPress = false` which should disable that. More fine grained control for that is currently worked on (see https://github.com/jb3rndt/PersistentBottomNavBarV2/pull/138).
If that doesnt help, please open a new issue.

**Comment by jb3rndt** [comment] 2024-04-12 19:09
I havent worked with go_router that much, so I dont know where the origin for this problem is located. Again, please open a new issue and provide the information required in the form (especially a minimal reproducible code example) to make debugging possible.

**Comment by bugrevealingbme** [comment] 2024-04-13 15:40
> I havent worked with go_router that much, so I dont know where the origin for this problem is located. Again, please open a new issue and provide the information required in the form (especially a minimal reproducible code example) to make debugging possible.

Actually, the problem is just that pop is changing the page. This problem didn't exist before. It came 2 versions ago. This is the problem we need to focus on, I can't make handleAndroidBackButtonPress = false because I use
