### ISSUE TITLE
hideNavigationBarWhenKeyboardShows not working as expected

### ISSUE THREAD

**Issue by lobobeebe** [jb3rndt/PersistentBottomNavBarV2#6] opened 2022-02-22 07:11 UTC
No matter the value of this property, the navBar is not hidden when the keyboard is shown.

<img width="346" alt="Screen Shot 2022-02-22 at 2 10 46 AM" src="https://user-images.githubusercontent.com/7032061/155080756-97bf6657-20b4-4b15-82c8-247d4bbccc28.png">

**Comment by jb3rndt** [comment] 2022-03-17 11:47
Should be fixed with version 4.1.4

**Closed** 2022-03-17 12:08 UTC

**Comment by pawarn** [comment] 2023-09-08 12:03
I'm facing the same issue while using Style 3.

The only difference is that I'm using the nested widget like MainBottomBar has another widget called FixedBottomBarMainScreen and this widget has the below bottom bar setup with 4 tabs. In those 4 tabs on the second tab, I have  TextFormField where need the keyboard.

here is the code snippet

`Scaffold(
      body: PersistentTabView(
        context,
        controller: _controller,
        screens: _buildScreens(),
        items: _navBarsItems(),
        confineInSafeArea: true,
        handleAndroidBackButtonPress: true,
        hideNavigationBarWhenKeyboardShows: true,
        stateManagement: false,
        hideNavigationBar: false,
        resizeToAvoidBottomInset: false,
        popAllScreensOnTapAnyTabs: false,
        popAllScreensOnTapOfSelectedTab: true,
        navBarHeight: 65,
        navBarStyle: NavBarStyle.style3,
        decoration: NavBarDecoration(
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(20), topLeft: Radius.circular(20)),
          colorBehindNavBar: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.grey,
              blurRadius: 10.0,
              spreadRadius: 0.0,
              offset: Offset(0.0, 2.0), // shadow direction: bottom right
            )
          ],
        ),
        onItemSelected: (int value) {
          print(value);
        },
        screenTransitionAnimation: ScreenTransitionAnimation(
          animateTabTransition: true,
          curve: Curves.ease,
          duration: Duration(milliseconds: 200),
        ),
      ),
    );`

**Comment by jb3rndt** [comment] 2023-09-17 09:27
Can you share a full example that demonstrates the issue? I was not able to reproduce the issue with the above snippet. Please also make sure to use the latest version of the package by running `dart pub upgrade`.
