### ISSUE TITLE
Navigation bar animation does not adhere to locale: left to right and right to left (e.g. Arabic and English). 

### ISSUE THREAD

**Issue by Abdullah-RashedMW** [jb3rndt/PersistentBottomNavBarV2#113] opened 2023-10-16 13:14 UTC
Navigation bar animation does not adhere to locale: left to right and right to left (e.g. Arabic and English). 
When using Easy Localization package, and switching from LTR and RTL from the package it does not apply to the bottom navigation bar tab switching animations.

**Comment by jb3rndt** [comment] 2023-12-06 14:07
Hi, which animation exactly do you expect to change? The sliding of the pages when switching tabs (isnt that independent of LTR and RTL)? Feel free to open a pull request if you have a solution.

**Comment by jb3rndt** [comment] 2023-12-06 14:16
Duplicate of https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/114

**Closed by jb3rndt** 2023-12-06 14:16 UTC
